name = "kumanoreta-gtfs-rt-proxy"
main = "src/index.js"
compatibility_date = "2026-06-18"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "*"
GTFS_RT_VEHICLE_POSITIONS_URL = "https://km.bus-vision.jp/realtime/toshibus_vpos_update.bin"
