name = "kumanoreta-gtfs-rt-proxy"
main = "src/index.js"
compatibility_date = "2026-06-18"
workers_dev = true

[vars]
ALLOWED_ORIGIN = "*"
GTFS_RT_VEHICLE_POSITIONS_URL = "https://km.bus-vision.jp/realtime/toshibus_vpos_update.bin"
GTFS_RT_TRIP_UPDATES_URL = "https://km.bus-vision.jp/realtime/toshibus_trip_update.bin"
GTFS_RT_VEHICLE_POSITIONS_URL_TOSHIBUS = "https://km.bus-vision.jp/realtime/toshibus_vpos_update.bin"
GTFS_RT_TRIP_UPDATES_URL_TOSHIBUS = "https://km.bus-vision.jp/realtime/toshibus_trip_update.bin"
GTFS_RT_VEHICLE_POSITIONS_URL_SANKOBUS = "https://km.bus-vision.jp/realtime/sankobus_vpos_update.bin"
GTFS_RT_TRIP_UPDATES_URL_SANKOBUS = "https://km.bus-vision.jp/realtime/sankobus_trip_update.bin"
GTFS_RT_VEHICLE_POSITIONS_URL_KUMABUS = "https://km.bus-vision.jp/realtime/kumabus_vpos_update.bin"
GTFS_RT_TRIP_UPDATES_URL_KUMABUS = "https://km.bus-vision.jp/realtime/kumabus_trip_update.bin"
GTFS_RT_VEHICLE_POSITIONS_URL_DENTETSU = "https://km.bus-vision.jp/realtime/dentetsu_vpos_update.bin"
GTFS_RT_TRIP_UPDATES_URL_DENTETSU = "https://km.bus-vision.jp/realtime/dentetsu_trip_update.bin"
